config/routes.rb
Firstapp::Application.routes.draw do

  resources :comments

  resources :projects

  devise_for :users
  root :to => 'pages#home'
  get 'about' => 'pages#about'
  get 'index_user' => 'projects#index_user'
  get 'users/:id/projects' => 'users#show', :as => :user_show
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :desvription, :image, :image_remote_url, :vid


  validates :title, presence: true
  validates :desvription, presence: true
	validates :user_id, presence: true
	validates_attachment :image, presence: true,
															 content_type: {content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
															 size: { less_than: 5.megabytes }


  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240>" }
  
  def image_remote_url=(url_value)
    self.image = URI.parse(url_value) unless url_value.blank?
    super
  end  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
          :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, 
 									:name, :bio, :city, :image
 	validate :bio, presence: true
 	validate :city, presence: true
 	validates_attachment :image, content_type: {content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']}, size: { less_than: 5.megabytes }
  # attr_accessible :title, :body

  has_many :projects, dependent: :destroy
  
  has_attached_file :image, styles: { medium: "240x180>" }
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
before_filter :authenticate_user!, except: [:index,:show]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
      format.js
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = current_user.projects.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = current_user.projects.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = current_user.projects.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
  def index_user 
    @projects = current_user.projects.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
		def show
		  @user = User.find(params[:id])
		  @projects = @user.projects
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer footer-fixed-bottom">
			<small>
				UNITE: Imagine Together. Create Together.
				Founder Nate Bodnar
			</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div class="navbar navbar-inverse">
   
        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a href="/" class="brand">
         <img alt="Unite" src="/assets/UniteBrand.jpg" width="45">
        </a>  
        <!-- Be sure to leave the brand out there if you want it shown -->
        <!--<%= link_to "UNITE", root_path, class: "brand" %>-->
        <!-- Everything you want hidden at 940px or less, place within here -->
        <div class="nav-collapse collapse">
        	<ul class="nav">
        	 <li><%= link_to "Home", root_path %></li>
  			   <li><%= link_to "About", about_path %></li>
           <li><%= link_to "Projects", projects_path %></li>
       	  </ul> 

       		<ul class="nav pull-right">
              <% if user_signed_in? %>
              <li><%= link_to "Add Project +", new_project_path %></li>
              <li><%= link_to "Your Projects", index_user_path %></li>
              <li><%= link_to "Profile", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              <% else %>
              <li><%= link_to "Create an Account", new_user_registration_path %></li>
          		<li><%= link_to "Login", new_user_session_path %></l>
                
              <% end %>   
       	  </ul> 

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>UNITE</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |name,msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
				<% end %>
			<%= yield %>
		</div>
	</body>
	<div class="container">
		<%= render 'layouts/footer' %>
	</div>	
</html>

app/views/pages/_video.html.erb
<iframe width="560" height="315" src="http://www.youtube.com/embed/S2hpqaDNz2Q" frameborder="0" allowfullscreen></iframe>

app/views/pages/about.html.erb
<div class="hero-unit">
<div class="row">
	<div class="span6">
		<h1>About</h1>
		<p>
			Photographers, Writers, Directors, Designers, Animators, Musicians and Coders create amazing work as individuals. What if these people were able to be easily brought together? Imagine what they could create.
		</p>
		<p>	
			UNITE is a project to bring these creative people together to create awesome media. From short films to new software, what you do with UNITE is up to you. UNITE allows users to post projects to receive feedback from other users. With the help of other's feedback, your project could reach a whole new level!
		</p>	
		<p>		
			UNITE brings all types of creative people together in one general location. The ability to get in contact with and network with other creative people allows for a unique experience.
			Post your individual projects or work as a team with other UNITE users to continue to express your creativity in what ever manner you see fit!
		</p>
		<p>
    	<%= mail_to "nathanieltbodnar@gmail.com", "Contact Us", class: "btn btn-large btn-primary" %>
		</p>
	<p>
		<% if user_signed_in? %>
		<% else %> 
		<%= link_to "Create an Account!",new_user_registration_path, class: "btn btn-large btn-primary"%>
		<% end %>
	</p>
</div>
</div>

app/views/pages/home.html.erb
<div class="row">
	<div class="span8 offset2">
		<div class="pic">
			<img alt="photo2" src="/assets/UniteO.jpg">
		</div>
			<!--<div id="myCarousel" class="carousel slide">
			  <div class="carousel-inner">
			    <div class="item active">
			    		<img alt="Unite" src="/assets/dark.jpg">
			    		<!--<div class="carousel-caption">	
			    </div>

			    <div class="item">
			  	<a href="">
			  		<img alt="photo2" src="/assets/UniteOrange.jpg">
			  	</a>	
			    </div>	
			   	
			    <div class="item">
			    	<img alt="DarkSide" src="/assets/Darkside of the moon test 2.jpg">
			    </div>
			  </div>
			  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
			  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
			</div> -->
		</div> 
</div>
<div class="steps">
	<div class="row">
		<div class= "span4">
			<center>
				<h1> Step 1: </h1>
				<p>Join UNITE to be able to use all features!</p>
				<p> <%= link_to "Create an Account!",new_user_registration_path, class: "btn btn-large btn-primary"%> </p>
			</center>
		</div>
		<div class= "span4">
			<center>
				<h1> Step 2: </h1>
				<p>Post your work for others to view!</p>
				<p>  <%= link_to "Post your Projects",new_project_path, class: "btn btn-large btn-primary"%> </p>
			</center>
		</div>
		<div class= "span4">
				<center>
				<h1> Step 3: </h1>
				<p>Team up with others to make awesome media!</p>
				<p>  <%= link_to "UNITE with Others", projects_path, class: "btn btn-large btn-primary"%> </p>
			</center>
		</div>
	</div>
	
</div>
<center>
<div class="span12">
			
			<center>
			<div class="block">
				<div class="quote">
					<p>
						"UNITE was created to bring creative people together. Creative people are stronger together. Together they can create awesome media."
					</p>
					<p>
						- Nate Bodnar, Founder of UNITE
					</p>
				</div>
			</div>
			</center>
		</div>
</center		

app/views/projects/_form.html.erb
<%= simple_form_for(@project, html: { class: "form-horizontal"}) do |f| %>

  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert aleart-error" %>
  <%= f.full_error :image_content_type, class: "alert aleart-error" %>

  	<%= f.input :title, as: :text, input_html: {rows: "1"}, label: 'Title' %>
  	<%= f.input :image, label: 'Upload an Image' %>
  	<%= f.input :image_remote_url, label: "Upload with a URL" %>
    <%= f.input :vid, label: "Link to More Info about your project (YouTube video, website, music download, etc.)" %>
    <%= f.input :desvription, as: :text, input_html: {rows: "30"}, label: 'Description' %>


  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary', :disable_with =>'Uploading Project...' %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="box">
	<%= link_to (image_tag project.image(:medium)), project %>
	
	<p class="description">
		<strong> <%= project.title %> </strong>	
	</p>
		
	<p>
		<%= link_to project.user.name, user_show_path(:id => project.user_id),class: "btn btn-mini btn-primary" %>

	  <% if current_user == project.user %>
		  <%= link_to (content_tag :i, "", class: "icon-edit icon-2x"), edit_project_path(project) %> 
		  <%= link_to (content_tag :i, "", class: "icon-remove icon-2x"), project, method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	</p>
</div>	
    

app/views/projects/edit.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'View', @project, class: "btn btn-mini btn-primary" %> 
<%= link_to 'Back', projects_path, class: "btn btn-mini btn-primary" %>
</div>
</div>
</div>

app/views/projects/index.html.erb
<div id="projects">
  <%= render @projects %>
</div>


<%= will_paginate @projects %>

app/views/projects/index.js.erb
$boxes = $('<%= j render(@projects) %>')

$('#projects').append( $boxes ).imagesLoaded( function(){
  $('#projects').masonry( 'reload');
});
<% if @projects.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@projects) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/projects/index_user.html.erb
<div id="projects">
  <%= render @projects %>
</div>

app/views/projects/new.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path, class: "btn btn-mini btn-primary" %>
</div>
</div>
</div>

app/views/projects/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @project.image %>

			<p>
				<strong><%= @project.title %> </strong>	
			</p>

			<p>
			  <%= @project.desvription %>
		  </p>

		  <p>
		  	<%= link_to "More Information", @project.vid, class: "btn btn-mini btn-primary" %>
		  </p>	
		  <p>
			  <%= link_to @project.user.name, user_show_path(:id => @project.user_id),class: "btn btn-mini btn-primary" %>
		  </p>
		  	<%= link_to (content_tag :i, "", class: "icon-arrow-left icon-2x"), projects_path %>
		  <% if current_user == @project.user %>
			  <%= link_to (content_tag :i, "", class: "icon-edit icon-2x"), edit_project_path(@project) %> 
			<% end %>  
			
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="hero-unit">
  <div class="box">
    <p>
  	  <a href="">
			  <img alt="profilepicture" src= <%= @user.image(:medium) %> >
		  </a>	
    </p>
  </div>

  <h1><%= @user.name %></h1>
  <p><strong><%= @user.city %></strong></p>
  <p><%= @user.bio %></p>
  <p>
    <%= mail_to @user.email, "UNITE with User", class: "btn btn-large btn-primary" %>
  </p>

</div>
<div id="projects">
<p>
	<%= render @projects %>
</p>
</div>